/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ellie_portaudiojni_PortAudioJNI */

#ifndef _Included_net_ellie_portaudiojni_PortAudioJNI
#define _Included_net_ellie_portaudiojni_PortAudioJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_initialize
  (JNIEnv *, jobject);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_terminate
  (JNIEnv *, jobject);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    enumerateDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_enumerateDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
