/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ellie_portaudiojni_PortAudioJNI */

#ifndef _Included_net_ellie_portaudiojni_PortAudioJNI
#define _Included_net_ellie_portaudiojni_PortAudioJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_initialize
  (JNIEnv *, jobject);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_terminate
  (JNIEnv *, jobject);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    enumerateDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_enumerateDevices
  (JNIEnv *, jobject);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    nativeOpenInputStream
 * Signature: (IIDJ)J
 */
JNIEXPORT jlong JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_nativeOpenInputStream
  (JNIEnv *, jclass, jint, jint, jdouble, jlong);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    nativeStartStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_nativeStartStream
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    nativeStopStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_nativeStopStream
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    nativeCloseStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_nativeCloseStream
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    nativeReadStream
 * Signature: (J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_nativeReadStream
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     net_ellie_portaudiojni_PortAudioJNI
 * Method:    nativeReadStreamOffset
 * Signature: (J[BIJ)J
 */
JNIEXPORT jlong JNICALL Java_net_ellie_portaudiojni_PortAudioJNI_nativeReadStreamOffset
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
